export const RegionCodes = [
  { id: 'AF', name: 'Afghanistan' },
  { id: 'AL', name: 'Albania' },
  { id: 'DZ', name: 'Algeria' },
  { id: 'AS', name: 'American Samoa' },
  { id: 'AD', name: 'Andorra' },
  { id: 'AO', name: 'Angola' },
  { id: 'AI', name: 'Anguilla' },
  { id: 'AQ', name: 'Antarctica' },
  { id: 'AG', name: 'Antigua and Barbuda' },
  { id: 'AR', name: 'Argentina' },
  { id: 'AM', name: 'Armenia' },
  { id: 'AW', name: 'Aruba' },
  { id: 'AU', name: 'Australia' },
  { id: 'AT', name: 'Austria' },
  { id: 'AZ', name: 'Azerbaijan' },
  { id: 'BS', name: 'Bahamas' },
  { id: 'BH', name: 'Bahrain' },
  { id: 'BD', name: 'Bangladesh' },
  { id: 'BB', name: 'Barbados' },
  { id: 'BY', name: 'Belarus' },
  { id: 'BE', name: 'Belgium' },
  { id: 'BZ', name: 'Belize' },
  { id: 'BJ', name: 'Benin' },
  { id: 'BM', name: 'Bermuda' },
  { id: 'BT', name: 'Bhutan' },
  { id: 'BO', name: 'Bolivia' },
  { id: 'BA', name: 'Bosnia and Herzegovina' },
  { id: 'BW', name: 'Botswana' },
  { id: 'BV', name: 'Bouvet Island' },
  { id: 'BR', name: 'Brazil' },
  { id: 'IO', name: 'British Indian Ocean Territory' },
  { id: 'BN', name: 'Brunei Darussalam' },
  { id: 'BG', name: 'Bulgaria' },
  { id: 'BF', name: 'Burkina Faso' },
  { id: 'BI', name: 'Burundi' },
  { id: 'KH', name: 'Cambodia' },
  { id: 'CM', name: 'Cameroon' },
  { id: 'CA', name: 'Canada' },
  { id: 'CV', name: 'Cape Verde' },
  { id: 'KY', name: 'Cayman Islands' },
  { id: 'CF', name: 'Central African Republic' },
  { id: 'TD', name: 'Chad' },
  { id: 'CL', name: 'Chile' },
  { id: 'CN', name: 'China' },
  { id: 'CX', name: 'Christmas Island' },
  { id: 'CC', name: 'Cocos (Keeling) Islands' },
  { id: 'CO', name: 'Colombia' },
  { id: 'KM', name: 'Comoros' },
  { id: 'CG', name: 'Congo' },
  { id: 'CD', name: 'Congo, the Democratic Republic of the' },
  { id: 'CK', name: 'Cook Islands' },
  { id: 'CR', name: 'Costa Rica' },
  { id: 'CI', name: "Cote D'Ivoire" },
  { id: 'HR', name: 'Croatia' },
  { id: 'CU', name: 'Cuba' },
  { id: 'CY', name: 'Cyprus' },
  { id: 'CZ', name: 'Czech Republic' },
  { id: 'DK', name: 'Denmark' },
  { id: 'DJ', name: 'Djibouti' },
  { id: 'DM', name: 'Dominica' },
  { id: 'DO', name: 'Dominican Republic' },
  { id: 'EC', name: 'Ecuador' },
  { id: 'EG', name: 'Egypt' },
  { id: 'SV', name: 'El Salvador' },
  { id: 'GQ', name: 'Equatorial Guinea' },
  { id: 'ER', name: 'Eritrea' },
  { id: 'EE', name: 'Estonia' },
  { id: 'ET', name: 'Ethiopia' },
  { id: 'FK', name: 'Falkland Islands (Malvinas)' },
  { id: 'FO', name: 'Faroe Islands' },
  { id: 'FJ', name: 'Fiji' },
  { id: 'FI', name: 'Finland' },
  { id: 'FR', name: 'France' },
  { id: 'GF', name: 'French Guiana' },
  { id: 'PF', name: 'French Polynesia' },
  { id: 'TF', name: 'French Southern Territories' },
  { id: 'GA', name: 'Gabon' },
  { id: 'GM', name: 'Gambia' },
  { id: 'GE', name: 'Georgia' },
  { id: 'DE', name: 'Germany' },
  { id: 'GH', name: 'Ghana' },
  { id: 'GI', name: 'Gibraltar' },
  { id: 'GR', name: 'Greece' },
  { id: 'GL', name: 'Greenland' },
  { id: 'GD', name: 'Grenada' },
  { id: 'GP', name: 'Guadeloupe' },
  { id: 'GU', name: 'Guam' },
  { id: 'GT', name: 'Guatemala' },
  { id: 'GN', name: 'Guinea' },
  { id: 'GW', name: 'Guinea-Bissau' },
  { id: 'GY', name: 'Guyana' },
  { id: 'HT', name: 'Haiti' },
  { id: 'HM', name: 'Heard Island and Mcdonald Islands' },
  { id: 'VA', name: 'Holy See (Vatican City State)' },
  { id: 'HN', name: 'Honduras' },
  { id: 'HK', name: 'Hong Kong' },
  { id: 'HU', name: 'Hungary' },
  { id: 'IS', name: 'Iceland' },
  { id: 'IN', name: 'India' },
  { id: 'ID', name: 'Indonesia' },
  { id: 'IR', name: 'Iran, Islamic Republic of' },
  { id: 'IQ', name: 'Iraq' },
  { id: 'IE', name: 'Ireland' },
  { id: 'IL', name: 'Israel' },
  { id: 'IT', name: 'Italy' },
  { id: 'JM', name: 'Jamaica' },
  { id: 'JP', name: 'Japan' },
  { id: 'JO', name: 'Jordan' },
  { id: 'KZ', name: 'Kazakhstan' },
  { id: 'KE', name: 'Kenya' },
  { id: 'KI', name: 'Kiribati' },
  { id: 'KP', name: "Korea, Democratic People's Republic of" },
  { id: 'KR', name: 'Korea, Republic of' },
  { id: 'KW', name: 'Kuwait' },
  { id: 'KG', name: 'Kyrgyzstan' },
  { id: 'LA', name: "Lao People's Democratic Republic" },
  { id: 'LV', name: 'Latvia' },
  { id: 'LB', name: 'Lebanon' },
  { id: 'LS', name: 'Lesotho' },
  { id: 'LR', name: 'Liberia' },
  { id: 'LY', name: 'Libya' },
  { id: 'LI', name: 'Liechtenstein' },
  { id: 'LT', name: 'Lithuania' },
  { id: 'LU', name: 'Luxembourg' },
  { id: 'MO', name: 'Macao' },
  { id: 'MK', name: 'Macedonia, the Former Yugoslav Republic of' },
  { id: 'MG', name: 'Madagascar' },
  { id: 'MW', name: 'Malawi' },
  { id: 'MY', name: 'Malaysia' },
  { id: 'MV', name: 'Maldives' },
  { id: 'ML', name: 'Mali' },
  { id: 'MT', name: 'Malta' },
  { id: 'MH', name: 'Marshall Islands' },
  { id: 'MQ', name: 'Martinique' },
  { id: 'MR', name: 'Mauritania' },
  { id: 'MU', name: 'Mauritius' },
  { id: 'YT', name: 'Mayotte' },
  { id: 'MX', name: 'Mexico' },
  { id: 'FM', name: 'Micronesia, Federated States of' },
  { id: 'MD', name: 'Moldova, Republic of' },
  { id: 'MC', name: 'Monaco' },
  { id: 'MN', name: 'Mongolia' },
  { id: 'ME', name: 'Montenegro' },
  { id: 'MS', name: 'Montserrat' },
  { id: 'MA', name: 'Morocco' },
  { id: 'MZ', name: 'Mozambique' },
  { id: 'MM', name: 'Myanmar' },
  { id: 'NA', name: 'Namibia' },
  { id: 'NR', name: 'Nauru' },
  { id: 'NP', name: 'Nepal' },
  { id: 'NL', name: 'Netherlands' },
  { id: 'NC', name: 'New Caledonia' },
  { id: 'NZ', name: 'New Zealand' },
  { id: 'NI', name: 'Nicaragua' },
  { id: 'NE', name: 'Niger' },
  { id: 'NG', name: 'Nigeria' },
  { id: 'NU', name: 'Niue' },
  { id: 'NF', name: 'Norfolk Island' },
  { id: 'MP', name: 'Northern Mariana Islands' },
  { id: 'NO', name: 'Norway' },
  { id: 'OM', name: 'Oman' },
  { id: 'PK', name: 'Pakistan' },
  { id: 'PW', name: 'Palau' },
  { id: 'PS', name: 'Palestine, State of' },
  { id: 'PA', name: 'Panama' },
  { id: 'PG', name: 'Papua New Guinea' },
  { id: 'PY', name: 'Paraguay' },
  { id: 'PE', name: 'Peru' },
  { id: 'PH', name: 'Philippines' },
  { id: 'PN', name: 'Pitcairn' },
  { id: 'PL', name: 'Poland' },
  { id: 'PT', name: 'Portugal' },
  { id: 'PR', name: 'Puerto Rico' },
  { id: 'QA', name: 'Qatar' },
  { id: 'RE', name: 'Reunion' },
  { id: 'RO', name: 'Romania' },
  { id: 'RU', name: 'Russian Federation' },
  { id: 'RW', name: 'Rwanda' },
  { id: 'BL', name: 'Saint Barthelemy' },
  { id: 'SH', name: 'Saint Helena' },
  { id: 'KN', name: 'Saint Kitts and Nevis' },
  { id: 'LC', name: 'Saint Lucia' },
  { id: 'MF', name: 'Saint Martin (French part)' },
  { id: 'PM', name: 'Saint Pierre and Miquelon' },
  { id: 'VC', name: 'Saint Vincent and the Grenadines' },
  { id: 'WS', name: 'Samoa' },
  { id: 'SM', name: 'San Marino' },
  { id: 'ST', name: 'Sao Tome and Principe' },
  { id: 'SA', name: 'Saudi Arabia' },
  { id: 'SN', name: 'Senegal' },
  { id: 'RS', name: 'Serbia' },
  { id: 'SC', name: 'Seychelles' },
  { id: 'SL', name: 'Sierra Leone' },
  { id: 'SG', name: 'Singapore' },
  { id: 'SX', name: 'Sint Maarten (Dutch part)' },
  { id: 'SK', name: 'Slovakia' },
  { id: 'SI', name: 'Slovenia' },
  { id: 'SB', name: 'Solomon Islands' },
  { id: 'SO', name: 'Somalia' },
  { id: 'ZA', name: 'South Africa' },
  { id: 'GS', name: 'South Georgia and the South Sandwich Islands' },
  { id: 'SS', name: 'South Sudan' },
  { id: 'ES', name: 'Spain' },
  { id: 'LK', name: 'Sri Lanka' },
  { id: 'SD', name: 'Sudan' },
  { id: 'SR', name: 'Suriname' },
  { id: 'SJ', name: 'Svalbard and Jan Mayen' },
  { id: 'SZ', name: 'Swaziland' },
  { id: 'SE', name: 'Sweden' },
  { id: 'CH', name: 'Switzerland' },
  { id: 'SY', name: 'Syrian Arab Republic' },
  { id: 'TW', name: 'Taiwan, Province of China' },
  { id: 'TJ', name: 'Tajikistan' },
  { id: 'TZ', name: 'Tanzania, United Republic of' },
  { id: 'TH', name: 'Thailand' },
  { id: 'TL', name: 'Timor-Leste' },
  { id: 'TG', name: 'Togo' },
  { id: 'TK', name: 'Tokelau' },
  { id: 'TO', name: 'Tonga' },
  { id: 'TT', name: 'Trinidad and Tobago' },
  { id: 'TN', name: 'Tunisia' },
  { id: 'TR', name: 'Turkey' },
  { id: 'TM', name: 'Turkmenistan' },
  { id: 'TC', name: 'Turks and Caicos Islands' },
  { id: 'TV', name: 'Tuvalu' },
  { id: 'UG', name: 'Uganda' },
  { id: 'UA', name: 'Ukraine' },
  { id: 'AE', name: 'United Arab Emirates' },
  { id: 'GB', name: 'United Kingdom' },
  { id: 'US', name: 'United States' },
  { id: 'UM', name: 'United States Minor Outlying Islands' },
  { id: 'UY', name: 'Uruguay' },
  { id: 'UZ', name: 'Uzbekistan' },
  { id: 'VU', name: 'Vanuatu' },
  { id: 'VE', name: 'Venezuela, Bolivarian Republic of' },
  { id: 'VN', name: 'Viet Nam' },
  { id: 'VG', name: 'Virgin Islands, British' },
  { id: 'VI', name: 'Virgin Islands, U.S.' },
  { id: 'WF', name: 'Wallis and Futuna' },
  { id: 'EH', name: 'Western Sahara' },
  { id: 'YE', name: 'Yemen' },
  { id: 'ZM', name: 'Zambia' },
  { id: 'ZW', name: 'Zimbabwe' },
];

export const Unit_types = [
  {
    unit_type: 'Area',
    units: {
      area_unit: ['m2', 'km2', 'ft2', 'ha'],
    },
  },
  {
    unit_type: 'AreaOverTime',
    units: {
      area_unit: ['m2', 'km2', 'ft2', 'ha'],
      time_unit: ['ms', 's', 'm', 'h', 'day', 'year'],
    },
  },
  {
    unit_type: 'ContainerOverDistance',
    units: {
      distance_unit: ['m', 'km', 'ft', 'mi', 'nmi'],
    },
  },
  {
    unit_type: 'Data',
    units: {
      data_unit: ['MB', 'GB', 'TB'],
    },
  },
  {
    unit_type: 'DataOverTime',
    units: {
      data_unit: ['MB', 'GB', 'TB'],
      time_unit: ['ms', 's', 'm', 'h', 'day', 'year'],
    },
  },
  {
    unit_type: 'Distance',
    units: {
      distance_unit: ['m', 'km', 'ft', 'mi', 'nmi'],
    },
  },
  {
    unit_type: 'DistanceOverTime',
    units: {
      distance_unit: ['m', 'km', 'ft', 'mi', 'nmi'],
      time_unit: ['ms', 's', 'm', 'h', 'day', 'year'],
    },
  },
  {
    unit_type: 'Energy',
    units: {
      energy_unit: ['Wh', 'kWh', 'MWh', 'MJ', 'GJ', 'TJ', 'BTU', 'therm', 'MMBTU'],
    },
  },
  {
    unit_type: 'money',
    units: {
      money_unit: [
        'usd',
        'afn',
        'dzd',
        'ars',
        'aud',
        'bhd',
        'brl',
        'cad',
        'kyd',
        'cny',
        'dkk',
        'egp',
        'eur',
        'hkd',
        'huf',
        'isk',
        'inr',
        'iqd',
        'ils',
        'jpy',
        'lbp',
        'mxn',
        'mad',
        'nzd',
        'nok',
        'qar',
        'rub',
        'sar',
        'sgd',
        'zar',
        'krw',
        'sek',
        'chf',
        'thb',
        'twd',
        'tnd',
        'try',
        'aed',
        'gbp',
      ],
    },
  },
  {
    unit_type: 'number',
    units: {},
  },
  {
    unit_type: 'NumberOverTime',
    units: {
      time_unit: ['ms', 's', 'm', 'h', 'day', 'year'],
    },
  },
  {
    unit_type: 'PassengerOverDistance',
    units: {
      distance_unit: ['m', 'km', 'ft', 'mi', 'nmi'],
    },
  },
  {
    unit_type: 'Time',
    units: {
      time_unit: ['ms', 's', 'm', 'h', 'day', 'year'],
    },
  },
  {
    unit_type: 'volume',
    units: {
      volume_unit: ['ml', 'l', 'm3', 'standard_cubic_foot', 'gallon_us', 'bbl'],
    },
  },
  {
    unit_type: 'weight',
    units: {
      weight_unit: ['g', 'kg', 't', 'ton', 'lb'],
    },
  },
  {
    unit_type: 'WeightOverDistance',
    units: {
      distance_unit: ['m', 'km', 'ft', 'mi', 'nmi'],
      weight_unit: ['g', 'kg', 't', 'ton', 'lb'],
    },
  },
  {
    unit_type: 'WeightOverTime',
    units: {
      time_unit: ['ms', 's', 'm', 'h', 'day', 'year'],
      weight_unit: ['g', 'kg', 't', 'ton', 'lb'],
    },
  },
];

export const Sources_database = [
  {
    source: 'ADEME',
    datasets: ['Base Carbone'],
  },
  {
    source: 'AIB',
    datasets: ['European Residual Mix'],
  },
  {
    source: 'BEIS',
    datasets: [
      'Greenhouse gas reporting: conversion factors 2016',
      'Greenhouse gas reporting: conversion factors 2017',
      'Greenhouse gas reporting: conversion factors 2018',
      'Greenhouse gas reporting: conversion factors 2019',
      'Greenhouse gas reporting: conversion factors 2020',
      'Greenhouse gas reporting: conversion factors 2021',
      'Greenhouse gas reporting: conversion factors 2022',
      'Greenhouse gas reporting: conversion factors 2023',
      "UK and England's carbon footprint to 2019",
      "UK and England's carbon footprint to 2020",
      "UK and England's carbon footprint to 2021",
    ],
  },
  {
    source: 'CAEP',
    datasets: ['China Products Carbon Footprint Factors Database'],
  },
  {
    source: 'CBAM',
    datasets: ['CBAM default values', 'Emission intensities at country level', 'Standard fuel emission factors'],
  },
  {
    source: 'CCF',
    datasets: ['Derived from CCF models'],
  },
  {
    source: 'Circular Ecology',
    datasets: ['ICE Database v3'],
  },
  {
    source: 'Climate TRACE',
    datasets: ['Climate TRACE Emissions Inventory'],
  },
  {
    source: 'CLP Group',
    datasets: ['CLP Sustainability Report'],
  },
  {
    source: 'CT',
    datasets: ['Climate Transparency Report'],
  },
  {
    source: 'DEWA',
    datasets: ['Sustainability Report'],
  },
  {
    source: 'DISER',
    datasets: [
      'National Greenhouse Account Factors',
      'National Greenhouse and Energy Reporting (Measurement) Determination (NGER)',
    ],
  },
  {
    source: 'ecoinvent',
    datasets: ['Cut-off Cumulative LCIA v3.10', 'Cut-off Cumulative LCIA v3.8'],
  },
  {
    source: 'EEA',
    datasets: ['Greenhouse gas emission intensity of electricity generation'],
  },
  {
    source: 'EEI',
    datasets: ['Electric Company Carbon Emissions and Electricity Mix Reporting Database'],
  },
  {
    source: 'Electricity Info',
    datasets: ['Fuel Mix of UK Domestic Electricity Suppliers'],
  },
  {
    source: 'EMA',
    datasets: ['Electricity Grid Emissions Factors and Upstream Fugitive Methane Emission Factor'],
  },
  {
    source: 'EPA',
    datasets: [
      'eGRID',
      'GHG Emission Factors Hub',
      'Supply Chain Factors Dataset (commodities)',
      'Supply Chain Greenhouse Gas Emission Factors v1.2',
    ],
  },
  {
    source: 'EPPO',
    datasets: ['CO2 Emission by Energy Type and Sector'],
  },
  {
    source: 'EXIOBASE',
    datasets: ['EXIOBASE 3'],
  },
  {
    source: 'GEMIS',
    datasets: ['GEMIS model and database v5.0'],
  },
  {
    source: 'GHG Protocol',
    datasets: ['GHG Emissions Calculation Tool'],
  },
  {
    source: 'GLEC',
    datasets: [
      'Default Fuel Efficiency and CO2e Intensity Factors',
      'Default fuel efficiency and GHG emission intensity values',
    ],
  },
  {
    source: 'Government of Canada',
    datasets: ['National Inventory Report'],
  },
  {
    source: 'Green-e',
    datasets: ['Green-e Residual Mix Emission Rates'],
  },
  {
    source: 'HKEI',
    datasets: ['HK Electric Investments Sustainability Report'],
  },
  {
    source: 'IEA',
    datasets: ['IEA Emissions Factors 2023', 'IEA Life Cycle Upstream Emission Factors 2023 (Pilot Edition)'],
  },
  {
    source: 'IPCC',
    datasets: ['2019 Refinement to the 2006 IPCC Guidelines for National Greenhouse Gas Inventories'],
  },
  {
    source: 'Market Economics Limited',
    datasets: [
      'Consumption emissions modelling - Cons EF 199 SUT',
      'Consumption emissions modelling - Cons EF 247 NZHES',
    ],
  },
  {
    source: 'MfE',
    datasets: ['Measuring emissions: A guide for organisations', 'Measuring Emissions: Detailed Guide'],
  },
  {
    source: 'Netherlands Enterprise Agency',
    datasets: ['The Netherlands: list of fuels and standard CO2 emission factors version of January 2022'],
  },
  {
    source: 'OEKOBAUDAT',
    datasets: ['OEKOBAUDAT 2023-I'],
  },
  {
    source: 'Private',
    datasets: [''],
  },
  {
    source: 'STC-Nestra B.V.',
    datasets: ['GHG emission factors for IWT'],
  },
  {
    source: 'UBA',
    datasets: [
      'Emissionsbilanz erneuerbarer Energietraeger',
      'Entwicklung der spezifischen Treibhausgas-Emissionen des deutschen Strommix',
      'ProBas',
    ],
  },
  {
    source: 'UNECE',
    datasets: ['Carbon Neutrality in the UNECE Region: Integrated Life-cycle Assessment of Electricity Sources'],
  },
  {
    source: 'WRAP',
    datasets: ['Scope 3 GHG Measurement and Reporting Protocols for Food and Drink'],
  },
];

export const Domains_types = [
  'general',
  'general_and_ecoinvent',
  'ecoinvent',
  'exiobase',
  'manufacturing',
  'manufacturing_and_ecoinvent',
];

export const FuelTypeByCategory = {
  energy: [
    'agricultural_byproducts',
    'anthracite_coal',
    'asphalt_and_road_oil',
    'avgas_gross',
    'avgas_net',
    'aviation_gasoline',
    'avtur_gross',
    'avtur_net',
    'avtur_renewable',
    'bagasse',
    'bamboo',
    'diesel',
    'biodiesel',
    'biodiesel_100percent',
    'biodiesel_hvo',
    'biodiesel_me',
    'biodiesel_me_tallow',
    'biodiesel_me_used_cooking_oil',
    'bioethanol',
    'biogas',
    'biomethane',
    'biomethane_compressed',
    'biomethane_liquified',
    'biopetrol',
    'biopropane',
    'bituminous_coal',
    'blast_furnace_gas',
    'burning_oil_gross',
    'burning_oil_net',
    'butane',
    'butane_gross',
    'butane_net',
    'butylene',
    'cng_gross',
    'cng_net',
    'coa_netl',
    'coal_and_coke_mixed_commercial_sector',
    'coal_and_coke_mixed_electric_power_sector',
    'coal_and_coke_mixed_industrial_coking',
    'coal_and_coke_mixed_industrial_sector',
    'coal_coke',
    'coal_gross',
    'coal_home_produced_gross',
    'coal_home_produced_net',
    'coal_net',
    'coke_oven_gas',
    'coking_coal_gross',
    'coking_coal_net',
    'crude_oil',
    'development_diesel',
    'development_petrol',
    'diesel_100_percent_mineral_gross',
    'diesel_100_percent_mineral_net',
    'diesel_biofuel_blend_gross',
    'diesel_biofuel_blend_net',
    'distillate_fuel_oil_no.1',
    'distillate_fuel_oil_no.2',
    'distillate_fuel_oil_no.4',
    'ethane',
    'ethanol_100percent',
    'ethylene',
    'fuel_gas',
    'fuel_oil_gross',
    'fuel_oil_net',
    'gas_oil_gross',
    'gas_oil_net',
    'grass_or_straw',
    'heavy_gas_oils',
    'isobutane',
    'isobutylene',
    'kerosene',
    'kerosene_type_jet_fuel',
    'kerosenetype_jet_fuel',
    'landfill_gas',
    'lignite_coal',
    'liquefied_petroleum_gases_lpg',
    'lng_gross',
    'lng_net',
    'lpg_gross',
    'lpg_net',
    'lubricants',
    'lubricants_gross',
    'lubricants_net',
    'marine_fuel_oil_gross',
    'marine_fuel_oil_net',
    'marine_gas_oil_gross',
    'marine_gas_oil_net',
    'methanol',
    'mixed_commercial_sector',
    'mixed_electric_power_sector',
    'mixed_industrial_coking',
    'mixed_industrial_sector',
    'motor_gasoline',
    'municipal_solid_waste',
    'naphtha_gross',
    'naphtha_lt_401degf',
    'naphtha_net',
    'natural_gas',
    'natural_gas_100_percent_mineral_blend_gross',
    'natural_gas_100_percent_mineral_blend_net',
    'natural_gas_gross',
    'natural_gas_net',
    'natural_gasoline',
    'north_american_hardwood',
    'north_american_softwood',
    'other_biomass_gases',
    'other_oil_gt_401degf',
    'other_petroleum_gas_gross',
    'other_petroleum_gas_net',
    'peat',
    'pentanes_plus',
    'petrochemical_feedstocks',
    'petrol_100_percent_mineral_petrol_gross',
    'petrol_100_percent_mineral_petrol_net',
    'petrol_biofuel_blend_gross',
    'petrol_biofuel_blend_net',
    'petroleum_coke_gross',
    'petroleum_coke_net',
    'petroleum_coke_solid',
    'plastics',
    'processed_fuel_oils_distillate_gross',
    'processed_fuel_oils_distillate_net',
    'processed_fuel_oils_residual_gross',
    'processed_fuel_oils_residual_net',
    'propane',
    'propane_gas',
    'propane_gross',
    'propane_net',
    'propylene',
    'refinery_miscellaneous_gross',
    'refinery_miscellaneous_net',
    'rendered_animal_fat',
    'renewable_petrol',
    'residual_fuel_oil_no.5',
    'residual_fuel_oil_no.6',
    'solid_byproducts',
    'special_naphtha',
    'straw',
    'sub_bituminous_coal',
    'tires',
    'unfinished_oils',
    'used_oil',
    'vegetable_oil',
    'waste_oils_gross',
    'waste_oils_net',
    'wood_and_wood_residuals',
    'wood_chips',
    'wood_logs',
    'wood_pellets',
  ],
  volume: [
    'asphalt_and_road_oil',
    'avgas',
    'aviation_gasoline',
    'avtur',
    'avtur_renewable',
    'biodiesel',
    'biodiesel_100percent',
    'biodiesel_hvo',
    'biodiesel_me',
    'biodiesel_me_tallow',
    'biodiesel_me_used_cooking_oil',
    'bioethanol',
    'biopetrol',
    'biopropane',
    'blast_furnace_gas',
    'burning_oil',
    'butane',
    'butylene',
    'cng',
    'coke_oven_gas',
    'crude_oil',
    'development_diesel',
    'development_petrol',
    'diesel',
    'diesel_100_percent_mineral',
    'diesel_biofuel_blend',
    'distillate_fuel_oil_no.1',
    'distillate_fuel_oil_no.2',
    'distillate_fuel_oil_no.4',
    'ethane',
    'ethanol_100percent',
    'ethylene',
    'fuel_gas',
    'fuel_oil',
    'gas_oil',
    'heavy_gas_oils',
    'isobutane',
    'isobutylene',
    'kerosene',
    'kerosene_type_jet_fuel',
    'kerosenetype_jet_fuel',
    'landfill_gas',
    'liquefied_petroleum_gases_lpg',
    'lng',
    'lpg',
    'lubricants',
    'marine_fuel_oil',
    'marine_gas_oil',
    'methanol',
    'motor_gasoline',
    'naphtha',
    'naphtha_lt_401degf',
    'natural_gas',
    'natural_gas_100_percent_mineral_blend',
    'natural_gasoline',
    'other_biomass_gases',
    'other_oil_gt_401degf',
    'other_petroleum_gas',
    'pentanes_plus',
    'petrochemical_feedstocks',
    'petrol',
    'petrol_biofuel_blend',
    'processed_fuel_oils_distillate',
    'processed_fuel_oils_residual',
    'propane',
    'propane_gas',
    'propylene',
    'rendered_animal_fat',
    'renewable_petrol',
    'residual_fuel_oil',
    'residual_fuel_oil_no.5',
    'residual_fuel_oil_no.6',
    'special_naphtha',
    'unfinished_oils',
    'used_oil',
    'vegetable_oil',
    'waste_oils',
  ],
  weight: [
    'agricultural_byproducts',
    'anthracite_coal',
    'avgas',
    'avtur',
    'avtur_renewable',
    'biodiesel',
    'biodiesel_hvo',
    'biodiesel_me',
    'biodiesel_me_tallow',
    'biodiesel_me_used_cooking_oil',
    'bioethanol',
    'biogas',
    'biomethane',
    'biomethane_compressed',
    'biomethane_liquified',
    'biopetrol',
    'biopropane',
    'bituminous_coal',
    'burning_oil',
    'butane',
    'cng',
    'coal',
    'coal_coke',
    'coal_home_produced',
    'coking_coal',
    'development_diesel',
    'development_petrol',
    'diesel_100_percent_mineral',
    'diesel_biofuel_blend',
    'fuel_oil',
    'gas_oil',
    'grass_or_straw',
    'landfill_gas',
    'lignite_coal',
    'lng',
    'lpg',
    'lubricants',
    'marine_fuel_oil',
    'marine_gas_oil',
    'methanol',
    'mixed_commercial_sector',
    'mixed_electric_power_sector',
    'mixed_industrial_coking',
    'mixed_industrial_sector',
    'municipal_solid_waste',
    'naphtha',
    'natural_gas',
    'natural_gas_100_percent_mineral_blend',
    'other_petroleum_gas',
    'peat',
    'petrol',
    'petrol_biofuel_blend',
    'petroleum_coke',
    'petroleum_coke_solid',
    'plastics',
    'processed_fuel_oils_distillate',
    'processed_fuel_oils_residual',
    'propane',
    'refinery_miscellaneous',
    'renewable_petrol',
    'solid_byproducts',
    'sub_bituminous_coal',
    'tires',
    'waste_oils',
    'wood_and_wood_residuals',
    'wood_chips',
    'wood_logs',
    'wood_pellets',
  ],
};
